apiVersion: v1
kind: Secret
metadata:
  name: {{.AppName}}
  labels:
    apps: {{.AppName}}
type: Opaque
data:
  mysql-root-password: YXBwc1Jvb3RQd2Q=
  mysql-password: YXBwc1B3ZA==
---
apiVersion: v1
kind: Service
metadata:
  name: {{.AppName}}
  labels:
    apps: {{.AppName}}
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    apps: {{.AppName}}
  type: ClusterIP
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.AppName}}-mysql-pv-claim
  labels:
    apps: {{.AppName}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard"
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{.AppName}}
  labels:
    apps: {{.AppName}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      apps: {{.AppName}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps: {{.AppName}}
    spec:
      containers:
      - name: {{.AppName}}
        image: {{.Image}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{.LimitCpu}}
            memory: {{.LimitMemory}}
          requests:
            cpu: {{.RequestCpu}}
            memory: {{.RequestMemory}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.AppName}}
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.AppName}}
              key: mysql-password
        - name: MYSQL_USER
          value: apps-user
        - name: MYSQL_DATABASE
          value: apps-db
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{.AppName}}-mysql-pv-claim
